#ifndef DEFINITIONS_H
#define DEFINITIONS_H
#define PIXELBUFFER_HEIGHT 700
#define PIXELBUFFER_WIDTH 800
#define SCREEN_HEIGHT 800
#define SCREEN_WIDTH 800
#define POLYGON_BUFFER_SIZE 100
#define SCREEN_TITLE "Paint C"
#define BG_COLOR WHITE
#endif // !DEFINITIONS_H
